version: "3.9"

services:
  database:
    image: bitnami/postgresql:latest
    container_name: emailn_database
    ports:
      - 54321:5432
    environment:
      - POSTGRESQL_DATABASE=docker
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
