### Variables 
@BASE = http://localhost:3000

### POST
POST {{BASE}}/campaigns
Content-Type: application/json

{
  "name": "Teste campanha",
  "content": "any content",
  "emails": ["teste@email.com"]
}

###
GET {{BASE}}/campaigns

