### Variables 
@BASE = http://localhost:3000

### Create
POST {{BASE}}/campaigns
Content-Type: application/json

{
  "name": "Teste campanha",
  "content": "any content",
  "emails": ["teste@email.com"]
}

### Get Many
GET {{BASE}}/campaigns

### Get One
GET {{BASE}}/campaigns/d08mt0es2kkk178l1d20

### Cancel
PATCH {{BASE}}/campaigns/d08mt0es2kkk178l1d20/cancel


